<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Alarma</name>
   <tag></tag>
   <elementGuidId>1f0911c6-6845-452d-a09e-d21e7015b95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b5-Dropdown_Alarma']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Dropdown_Alarma</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f309e73f-2f67-42c6-8cf7-0d3bfe804e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>87bc2312-5aa1-4fc5-be88-263876e75dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c449076-b810-4355-ae1c-2e69f2592588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Dropdown_Alarma</value>
      <webElementGuid>33c1bdec-9a55-4f6c-9388-cd49b676ac57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione el alarmaALERTANORMALCRÍTICO</value>
      <webElementGuid>2c609883-fdd1-409d-a138-c080cf169378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Dropdown_Alarma&quot;)</value>
      <webElementGuid>08553582-06cc-470c-944f-a5c286224d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b5-Dropdown_Alarma']</value>
      <webElementGuid>f59ef912-f3cd-4f2e-b1e7-ffdc279d08c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Dropdown_Alarma-container']/select</value>
      <webElementGuid>b21418d7-c0c4-40f2-a9e7-ee965f28968e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alarma'])[1]/following::select[1]</value>
      <webElementGuid>ec863412-1a7d-4291-bd11-9cc17bbc3f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número del aviso'])[1]/following::select[1]</value>
      <webElementGuid>d1faa4e5-e970-43f8-a4ec-a41c5d2f1e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre del cliente'])[1]/preceding::select[1]</value>
      <webElementGuid>acf82c37-4da9-4441-b43d-a8312a4f981a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubicación técnica del cliente'])[1]/preceding::select[1]</value>
      <webElementGuid>2e90922c-7b4b-497b-b068-51676a750f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6fe3302b-89cf-4eb0-aa7a-a2c71616497f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b5-Dropdown_Alarma' and (text() = 'Seleccione el alarmaALERTANORMALCRÍTICO' or . = 'Seleccione el alarmaALERTANORMALCRÍTICO')]</value>
      <webElementGuid>ff68756c-1a58-498e-8518-cc662d9b690a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
